name = "Panaderos-Hero"
license = "MIT"
licenselink = "https://github.com/lieuwebakker/panaderos-hero-theme/blob/master/LICENSE/blob/master/LICENSE"
description = "Panaderos-Hero is a multipurpose theme with fullscreen hero images and fullwidth sections. It contains content types for a business or portfolio site."

homepage = "https://github.com/lieuwebakker/panaderos-hero-theme/blob/master/LICENSE"
demosite = "https://hugo-hero.netlify.app/"

tags = ["responsive","minimal","clean","company","portfolio","bootstrap","zerostatic"]
features = ["services","work","fullwidth","hero images"]

[author]
  name = "JawSome.Orbit"
